/*
  Module    : CTAPALMDB
  Filename  : CtApAlmDbSources.h
  Desc      : Alarm Sources Macro define

  Generated by dtcdb.py version 1.8.0.0 at 2025-06-06 11:33:09.605452
  Source file: C:/ALM/DtcDb/Input_NG13_00_00/DtcDB.xml
*/

#ifndef CTAPALMDBSOURCES_H
#define CTAPALMDBSOURCES_H

#define CTAPALMDB_NO_SRC                0x0000
#define CTAPALMDB_ACM_SRC               0x0100
#define CTAPALMDB_ATP_SRC               0x0200
#define CTAPALMDB_CEG_SRC               0x0300
#define CTAPALMDB_DBT_SRC               0x0400
#define CTAPALMDB_ECM_SRC               0x0500
#define CTAPALMDB_FLM_SRC               0x0600
#define CTAPALMDB_FUM_SRC               0x0700
#define CTAPALMDB_HVAC_SRC              0x0800
#define CTAPALMDB_IMM_SRC               0x0900
#define CTAPALMDB_ITM_SRC               0x0A00
#define CTAPALMDB_LIM_SRC               0x0B00
#define CTAPALMDB_MECU_SRC              0x0C00
#define CTAPALMDB_MFA_SRC               0x0D00
#define CTAPALMDB_MSA_SRC               0x0E00
#define CTAPALMDB_NOM_SRC               0x0F00
#define CTAPALMDB_PCU_SRC               0x1000
#define CTAPALMDB_RAM_SRC               0x1100
#define CTAPALMDB_RTC_SRC               0x1200
#define CTAPALMDB_T2F_SRC               0x1300
#define CTAPALMDB_TBM_SRC               0x1400
#define CTAPALMDB_TCU_SRC               0x1500
#define CTAPALMDB_TPC_SRC               0x1600
#define CTAPALMDB_TPC2_SRC              0x1700
#define CTAPALMDB_UCM_SRC               0x1800
#define CTAPALMDB_VBM_SRC               0x1900
#define CTAPALMDB_VBM_ACM_SRC           0x1901
#define CTAPALMDB_VBM_ALIVEMONITOR_SRC  0x1902
#define CTAPALMDB_VBM_ALM_SRC           0x1903
#define CTAPALMDB_VBM_CNT_SRC           0x1904
#define CTAPALMDB_VBM_EEM_SRC           0x1905
#define CTAPALMDB_VBM_ENG_SRC           0x1906
#define CTAPALMDB_VBM_EXL_SRC           0x1907
#define CTAPALMDB_VBM_FAN_SRC           0x1908
#define CTAPALMDB_VBM_FEH_SRC           0x1909
#define CTAPALMDB_VBM_FKM_SRC           0x190A
#define CTAPALMDB_VBM_FL_SRC            0x190B
#define CTAPALMDB_VBM_FPTO_SRC          0x190C
#define CTAPALMDB_VBM_FTL_SRC           0x190D
#define CTAPALMDB_VBM_HYD_SRC           0x190E
#define CTAPALMDB_VBM_I7P_SRC           0x190F
#define CTAPALMDB_VBM_ICL_SRC           0x1910
#define CTAPALMDB_VBM_IGN_SRC           0x1911
#define CTAPALMDB_VBM_INL_SRC           0x1912
#define CTAPALMDB_VBM_NEM_SRC           0x1913
#define CTAPALMDB_VBM_REH_SRC           0x1914
#define CTAPALMDB_VBM_RPTO_SRC          0x1915
#define CTAPALMDB_VBM_SFA_SRC           0x1916
#define CTAPALMDB_VBM_SUPPLYMONITOR_SRC 0x1917
#define CTAPALMDB_VBM_TB_SRC            0x1918
#define CTAPALMDB_VBM_VDC_SRC           0x1919
#define CTAPALMDB_ALL_MAX_SRC           0x191A
#define CTAPALMDB_ERROR_MIN_SRC         0xFE00
#define CTAPALMDB_ERROR_MAX_SRC         0xFEFF
#define CTAPALMDB_NOT_AVAILABLE_MIN_SRC 0xFF00
#define CTAPALMDB_NOT_AVAILABLE_MAX_SRC 0xFFFF

#define CTAPALMDB_MAX_SRC               (CTAPALMDB_NOT_AVAILABLE_MAX_SRC)
#endif // CTAPALMDBSOURCES_H
