/*
  Module    : CTAPALMDB
  Filename  : CtApAlmDb.h

  Generated by dtcdb.py version 1.8.0.0 at 2025-06-06 11:33:09.609995
  Source file: C:/ALM/DtcDb/Input_NG13_00_00/DtcDB.xml
*/

#ifndef CTAPALMDB_H
#define CTAPALMDB_H
#include <stdint.h>
#include <stdbool.h>

#define CTAPALMDB_MAGIC_NUMBER (0x0C9FF27F)

typedef enum {
  INIT_OK                = 0x00,
  INIT_BAD_CRC           = 0x01,
  INIT_BAD_COMPATIBILITY = 0x02,
  INIT_BAD_SPNFMI        = 0x04,
  INIT_BAD_DTC_TYPE      = 0x08,
  INIT_BAD_SPNFMI_SRC    = 0x10,
} InitStatus_T;

// DTC Data Base Version
extern void get_DtcDbVers(uint8_t *pMajor, uint8_t *pMedium, uint8_t *pMinor);
extern void get_DtcDbVers4Bytes(uint8_t *pMajor, uint8_t *pMediumH, uint8_t *pMediumL, uint8_t *pMinor);

extern InitStatus_T init_lookup();
extern uint8_t  const * const get_DtcDbStartAddress();
extern uint32_t               get_DtcDbCrc();
extern char     const * const get_GenToolvers();
extern char     const * const get_AlmDBdateExtract();

// SPN/FMI TYPEs enums definitions
typedef enum {
  CTAPALMDB_CUMMINS5_INDEX = (uint8_t)0x00,
  CTAPALMDB_FPT_INDEX      = (uint8_t)0x01,
  CTAPALMDB_FPTST5_INDEX   = (uint8_t)0x02,
  CTAPALMDB_FPTT4F_INDEX   = (uint8_t)0x03,
  CTAPALMDB_FUM_INDEX      = (uint8_t)0x04,
  CTAPALMDB_LIM_INDEX      = (uint8_t)0x05,
  CTAPALMDB_RAM_INDEX      = (uint8_t)0x06,
  CTAPALMDB_MAX_INDEX     
} T_SrcIndex;

// SPN/FMI API functions declarations
extern uint16_t SpnFmiLookup(T_SrcIndex srcindex, uint32_t spn_u32, uint8_t fmi_u8);
extern int      get_SpnFmiArraySizeInBytes();

// DTC TYPEs enums definitions
typedef enum {
  CTAPALMDB_NO_TYPE      = 0x00,
  CTAPALMDB_ERROR_TYPE   = 0x01,
  CTAPALMDB_ICON_TYPE    = 0x02,
  CTAPALMDB_INFO_TYPE    = 0x04,
  CTAPALMDB_PING_TYPE    = 0x08,
  CTAPALMDB_SILENT_TYPE  = 0x10,
  CTAPALMDB_WARNING_TYPE = 0x20,
  CTAPALMDB_MAX_TYPE    
} T_DtcType;

// DTC TYPEs API functions declarations
extern T_DtcType DtcTypeLookup(uint16_t dtc_u16);
extern int       get_DtcArraySizeInBytes();

// SPN/FMI sources and config type enum definitions
#define CTAPALMDB_NOT_AVAILABLE_CFG 0xFF
typedef enum {
  CTAPALMDB_NO_CFG             = (uint8_t)0x00,
  CTAPALMDB_FPT_STAGE4_CFG     = (uint8_t)0x01,
  CTAPALMDB_FPT_STAGE5_CFG     = (uint8_t)0x03,
  CTAPALMDB_FPT_STAGE3A_CFG    = (uint8_t)0x05,
  CTAPALMDB_FPT_CHINAIV_CFG    = (uint8_t)0x06,
  CTAPALMDB_CUMMINS_STAGE5_CFG = (uint8_t)0x07,
  CTAPALMDB_RAM_CFG            = (uint8_t)0xFB,
  CTAPALMDB_LIM_CFG            = (uint8_t)0xFC,
  CTAPALMDB_FUM_CFG            = (uint8_t)0xFD,
  CTAPALMDB_MAX_CFG            = (uint8_t)0xFF,
} T_SrcCfg;
// SPN/FMI sources and config API functions declarations
extern T_SrcIndex SpnFmiSrcLookup(uint16_t src_u16, uint8_t cfg_u8);
extern int        get_SpnFmiSrcArraySizeInBytes();


#ifndef CTAPALMDB_DTC_NOT_VALID
#    define CTAPALMDB_DTC_NOT_VALID	0xFFFF
#endif
#endif // CTAPALMDB_H
