#ifndef CTAPALMMODULEVERSION_H
#define CTAPALMMODULEVERSION_H

#define MODULE_VERSION_HIGH		0x00
#define MODULE_VERSION_MIDDLE	0x09
#define MODULE_VERSION_LOW		0x08

#endif // CTAPALMMODULEVERSION_H