
#ifndef CTAPALM_ALIVE_STATES
#define CTAPALM_ALIVE_STATES

#define ALIVE_STATE_INITIALISATION	(0x00)
#define ALIVE_STATE_ACTIVE			(0x01)
#define ALIVE_STATE_PREPARING_SLEEP	(0x20)
#define ALIVE_STATE_SLEEP_POSSIBLE	(0x21)
#define ALIVE_STATE_SLEEP			(0x22)

#endif // CTAPALM_ALIVE_STATES