/*
  Module    : CTAPALMDB
  Filename  : CtApAlmDbType.h
  Desc      : Alarm Database Type declaration

  Generated by dtcdb.py version 1.8.0.0 at 2025-06-06 11:33:09.608473
  Source file: C:/ALM/DtcDb/Input_NG13_00_00/DtcDB.xml
*/

#ifndef CTAPALMDBTYPE_H
#define CTAPALMDBTYPE_H
#include <stdint.h>
#include "CtApAlmDb.h"

#define CTAPALMDB_MAGIC_NUMBER (0x0F15BC56)

#define SPNFMI_OFFSET_VALUE (0x00000050)
#define DTCTYP_OFFSET_VALUE (0x0000BAA4)
#define SPNFMISRC_OFFSET_VALUE (0x0001BFDC)
#define CRC_OFFSET_VALUE (0x0001BFFC)
#define CALC_CRC_VALUE (0xB21D7D76)

// SPN/FMI types and structs definitions
typedef struct {
  uint16_t offset_left_u16;
  uint16_t offset_right_u16;
  uint16_t dummy_1_u16;
  uint16_t dummy_2_u16;
  uint16_t dummy_3_u16;
  uint16_t dummy_4_u16;
  uint16_t dummy_5_u16;
} T_SpnFmiNode;

typedef uint16_t T_SpnFmiLeaf[CTAPALMDB_MAX_INDEX];

typedef struct {
  uint32_t tag_u32;
  uint8_t  rank_u8;
  union {
    T_SpnFmiNode node_t;
    T_SpnFmiLeaf leaf_t;
  } _n;
} T_SpnFmiNodes;

#define SPNFMI_ARRAY_LEN (2385)

// DTC TYPEs types and structs definitions
typedef struct {
  uint16_t offset_left_u16;
  uint16_t offset_right_u16;
} T_DtcNode;

typedef struct {
  uint16_t type_u16;
  uint16_t dummy_u16;
} T_DtcLeaf;

typedef struct {
  uint16_t tag_u16;
  uint8_t  rank_u8;
  union {
    T_DtcNode node_t;
    T_DtcLeaf leaf_t;
  } _n;
} T_DtcNodes;

#define DTCS_ARRAY_LEN (8359)

// SPN/FMI sources and config types and structs definitions
typedef struct {
  uint16_t src_u16;
  uint8_t  cfg_u8;
  uint8_t  index_u8;
} T_SpnFmiSrc;

#define SPNFMISRC_ARRAY_LEN (8)


#define TOOL_VERS_LEN	(16)
#define DB_VERS_LEN		(16)
#define DB_DATE_LEN		(32)

typedef struct {
  char tool_vers[TOOL_VERS_LEN];
  char db_vers[DB_VERS_LEN];
  char db_date[DB_DATE_LEN];
  uint32_t SpnFmiNodes_offset_u32; // Offset to SPN/FMI Array from Header start address
  uint32_t DtcNodes_offset_u32; // Offset to DTC type Array from Header start address
  uint32_t SpnFmiSrc_offset_u32; // Offset to SPN/FMI Suppliers Array from Header start address
  uint32_t Crc_offset_u32; // Offset to CRC field from Header start address
} T_CtApAlmDbHeader;

typedef struct {
  T_CtApAlmDbHeader header_t;
  T_SpnFmiNodes SpnFmiNodes_t[SPNFMI_ARRAY_LEN];
  T_DtcNodes DtcNodes_t[DTCS_ARRAY_LEN];
  T_SpnFmiSrc SpnFmiSrc_t[SPNFMISRC_ARRAY_LEN];
  uint32_t crc_u32;
} T_CtApAlmDatabase;

extern T_CtApAlmDatabase const CtApAlmDatabase_t;
#endif // CTAPALMDBTYPE_H
